const DEFAULT_PAGE = 1
const DEFAULT_PHOTOS_LIMIT = 5

const DEFAULT_PHOTOS_PAGINATION = {
  page: DEFAULT_PAGE,
  limit: DEFAULT_PHOTOS_LIMIT
}

const CLEARANCE_FOR_ADDITIONAL_LOADING = 0.05

export { DEFAULT_PHOTOS_PAGINATION, CLEARANCE_FOR_ADDITIONAL_LOADING, DEFAULT_PAGE, DEFAULT_PHOTOS_LIMIT }
